package mybatis.model;

public class SysRolePrivilege {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_privilege.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_privilege.privilege
     *
     * @mbggenerated
     */
    private Long privilege;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_privilege.role_id
     *
     * @return the value of sys_role_privilege.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_privilege.role_id
     *
     * @param roleId the value for sys_role_privilege.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_privilege.privilege
     *
     * @return the value of sys_role_privilege.privilege
     *
     * @mbggenerated
     */
    public Long getPrivilege() {
        return privilege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_privilege.privilege
     *
     * @param privilege the value for sys_role_privilege.privilege
     *
     * @mbggenerated
     */
    public void setPrivilege(Long privilege) {
        this.privilege = privilege;
    }
}